name: Deploy Next.js

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -o TCPKeepAlive=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
        # Carregar o ambiente do usuário corretamente, incluindo o NVM
        source /home/valkyriecheckout-checkout/.nvm/nvm.sh
        cd htdocs/checkout.valkyriecheckout.com/checkout-valkyrie|| exit
        git pull origin main
        npm install
        npm run build
        cp .env .next
        pm2 restart checkout || exit
        EOF
